### ISSUE TITLE
Have all Public methods return errors

### ISSUE THREAD

**Issue by polds** [kyani-inc/storage#12]
Working on the BoltDB implementation there are several instances I can see that the whole implementation could fail due to the fact no errors can be bubbled back to the user, I propose `New()`, `Get()` and `Flush()` have errors return this would have the possibility to resolve #8 .

**Comment by crit** [comment]
I feel like `Flush()` should be idempotent and so shouldn't ever error. `New()` I think makes the most sense though it complicates the usage a bit. I'm on the fence about `Get()`.

**Comment by crit** [comment]
Check #13
